version: '3'

services:
  frontend:
    build: './frontend'
    ports: [3000:3000]
    working_dir: /frontend
    container_name: app_frontend
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '3000']
      interval: 10s
      retries: 5
    depends_on:
      - db
  backend:
    build: './backend'
    ports: [5000:5000]
    working_dir: /backend
    container_name: app_backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
      interval: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=5000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgresliers
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=secret
    volumes:
      - ./backend:/backend
  db:
    image: postgres:latest
    container_name: app_db
    ports: [5432:5432]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresliers
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 10s
      retries: 5